import base64
import logging

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
from odoo.tools import DEFAULT_SERVER_DATE_FORMAT
from ..models.mbank_request import MBankAuthMethods, MBankApiException, MBankRequest

_logger = logging.getLogger(__name__)


class GetSessionToken(models.TransientModel):
    """Get Background session token wizard.
    Authorize by signature and retrieve background session token from the service.

    User Flow:
    1.1. `button_get_login_to_sign_file`
    1.2. `button_download_login_to_sign`
    1.3. Sign file using CAdES signature (include data).
    1.4. Upload signed file into `signed_login_file_id`
    1.5. `button_get_login_token`

    2.1. `button_get_token_to_sign`
    2.2. `button_download_token_to_sign`
    2.3. Sign file using CAdES signature (include data).
    2.4. Upload signed file into `signed_file_id`
    2.5. `button_get_session_token`
    """

    _name = 'trilab_mbank.get.session.token.wizard'
    _description = 'Trilab mBank Get Session Token Wizard'

    journal_ids = fields.Many2many(
        'account.journal', default=lambda self: self.env.context.get('active_ids'), readonly=True
    )
    session_expiration = fields.Datetime(
        'Session Expiration date', help='Session Expiration date could not be bigger than certificate validity date.'
    )

    # Step One - Authentication by Downloading login file to sign by user,
    # uploading signed file and retrieving authentication token from the service
    login_to_sign_file_id = fields.Many2one('ir.attachment')
    signed_login_file_id = fields.Many2one('ir.attachment')
    signed_login_file_datas = fields.Binary(
        string='Signed Login File ', related='signed_login_file_id.datas', readonly=False
    )
    signed_login_file_name = fields.Char(string='Signed Login File Name', related='signed_login_file_id.name')
    auth_token = fields.Char()

    # Step Two - Creating Background Session using authentication token generated by the service in previous step
    token_to_sign_file_id = fields.Many2one('ir.attachment')
    signed_file_id = fields.Many2one('ir.attachment')
    signed_file_datas = fields.Binary(string='Signed Token File', related='signed_file_id.datas', readonly=False)
    signed_file_name = fields.Char(string='Signed Token File Name', related='signed_file_id.name')

    def _get_token_to_sign_filename(self):
        return _('token-to-sign-%s.txt', fields.Date.context_today(self).strftime(DEFAULT_SERVER_DATE_FORMAT))

    def _get_login_to_sign_filename(self):
        return _('login-to-sign-%s.txt', fields.Date.context_today(self).strftime(DEFAULT_SERVER_DATE_FORMAT))

    def button_get_token_to_sign(self):
        self.ensure_one()

        if not self.auth_token:
            raise ValidationError(_('Please Login'))

        req = self._get_api_client(self.journal_ids)

        try:
            token_to_sign = req.init_create_background_session(self.auth_token, self.session_expiration)
            self.token_to_sign_file_id = self.env['ir.attachment'].create(
                dict(
                    res_id=self.id,
                    res_model=self._name,
                    name=self._get_token_to_sign_filename(),
                    type='binary',
                    datas=base64.b64encode(token_to_sign.encode('utf-16le')),
                )
            )

        except (MBankApiException, ValidationError) as err:
            _logger.error('button_get_token_to_sign error occurred', exc_info=err)
            raise ValidationError(str(err)) from err

        return self.get_wizard_action()

    def get_wizard_action(self):
        self.ensure_one()
        # noinspection PyProtectedMember
        action = self.env['ir.actions.act_window']._for_xml_id('trilab_mbank.get_session_token_wizard_action')
        action['res_id'] = self.id
        return action

    def button_download_token_to_sign(self):
        self.ensure_one()
        if self.token_to_sign_file_id:
            return {
                'type': 'ir.actions.act_url',
                'url': f'/web/content/ir.attachment/{self.token_to_sign_file_id.id}/datas?download=True',
                'target': 'self',
            }

    def button_download_login_to_sign(self):
        self.ensure_one()
        if self.login_to_sign_file_id:
            return {
                'type': 'ir.actions.act_url',
                'url': f'/web/content/ir.attachment/{self.login_to_sign_file_id.id}/datas?download=True',
                'target': 'self',
            }

    def button_get_session_token(self):
        self.ensure_one()

        if not self.signed_file_id:
            raise ValidationError(_('Please upload in Signed Token File'))

        req = self._get_api_client(self.journal_ids)

        try:
            response = req.create_background_session(self.auth_token, self.signed_file_datas, self.session_expiration)
            self.journal_ids.x_mbank_session_token = response.generatedToken
        except (MBankApiException, ValidationError) as err:
            _logger.error('button_get_session_token error occurred', exc_info=err)
            raise ValidationError(str(err)) from err

    @api.onchange('signed_file_datas')
    def create_signed_file_attachment(self):
        if self.signed_file_name and self.signed_file_datas:
            self.signed_file_id = self._create_attachment(filename=self.signed_file_name, datas=self.signed_file_datas)

    @api.onchange('signed_login_file_datas')
    def create_signed_login_file_attachment(self):
        if self.signed_login_file_name and self.signed_login_file_datas:
            self.signed_login_file_id = self._create_attachment(
                filename=self.signed_login_file_name, datas=self.signed_login_file_datas
            )

    def _create_attachment(self, filename, datas):
        self.ensure_one()

        try:
            datas = datas.decode(errors='ignore')
        except UnicodeDecodeError:
            datas = ''

        # PEM file
        if '-----BEGIN PKCS7-----' in datas:
            datas = datas.replace('-----BEGIN PKCS7-----', '')
            datas = datas.replace('-----END PKCS7-----', '')
            datas = datas.replace('\n', '')
            datas = datas.replace('\r', '')
            datas = datas.encode()

            return (
                self.env['ir.attachment']
                .create(dict(name=filename, type='binary', datas=datas, res_id=self.id, res_model=self._name))
                .id
            )

        # DER file
        else:
            return (
                self.env['ir.attachment']
                .create(dict(name=filename, type='binary', datas=datas, res_id=self.id, res_model=self._name))
                .id
            )

    def default_get(self, fields_list):
        defaults = super(GetSessionToken, self).default_get(fields_list)

        journal_ids = defaults.get('journal_ids')
        if journal_ids:
            journal_ids = self.env['account.journal'].browse(journal_ids[0][2])
            self._validate_journals(journal_ids)
            self._close_old_sessions(journal_ids)
        return defaults

    def _close_old_sessions(self, journal_ids):
        if not any(journal_ids.mapped('x_mbank_session_token')):
            return

        try:
            req = self._get_api_client(journal_ids)
            for session_token in filter(None, set(journal_ids.mapped('x_mbank_session_token'))):
                req.close_background_session(session_token)
            journal_ids.x_mbank_session_token = False
        except (MBankApiException, ValidationError) as err:
            journal_ids.x_mbank_session_token = False
            _logger.error(f'close_background_session error occurred.', exc_info=err)
            raise ValidationError(str(err)) from err
        finally:
            self.env.cr.commit()

    @staticmethod
    def _validate_journals(journal_ids):
        checks = (
            all(
                journal_ids.mapped(
                    lambda _j: _j.bank_statements_source == 'mbank'
                    and _j.x_mbank_auth_method == MBankAuthMethods.BACKGROUND_SESSION.value
                )
            ),
            len(set(journal_ids.mapped('x_mbank_user_id'))) == 1,
            len(set(journal_ids.mapped('x_mbank_test'))) == 1,
        )

        if not all(checks):
            raise ValidationError(
                _(
                    'Some journals are incompatible with this action. Make sure all journals have:\n'
                    '- same `User ID`\n'
                    '- `Bank Feeds` set as `mBank Polska`\n'
                    '- `Authentication Method` set to `Long term Session`\n'
                    '- `Test` is enabled or disabled across all journals'
                )
            )

    @staticmethod
    def _get_api_client(journal_ids):
        journal = journal_ids[:1]

        journal.ensure_one()

        return MBankRequest(
            journal_ids.mapped('x_mbank_dik'),
            journal.x_mbank_user_id,
            MBankAuthMethods(journal.x_mbank_auth_method),
            is_test=journal.x_mbank_test,
            enable_logging=journal.x_mbank_enable_logging,
        )

    def button_get_login_to_sign_file(self):
        self.ensure_one()

        req = self._get_api_client(self.journal_ids)

        try:
            token_to_sign = req.init_signature_login()

            self.login_to_sign_file_id = self.env['ir.attachment'].create(
                dict(
                    res_id=self.id,
                    res_model=self._name,
                    name=self._get_login_to_sign_filename(),
                    type='binary',
                    datas=base64.b64encode(token_to_sign.encode('utf-16le')),
                )
            )

        except MBankApiException as err:
            _logger.error('button_get_login_to_sign error occurred', exc_info=err)
            raise ValidationError(str(err)) from err

        return self.get_wizard_action()

    def button_get_login_token(self):
        self.ensure_one()

        if not self.signed_login_file_id:
            raise ValidationError(_('Please upload in Signed Login File'))

        req = self._get_api_client(self.journal_ids)

        try:
            response = req.finish_signature_login(self.signed_login_file_datas)
            self.auth_token = response.generatedToken
        except (MBankApiException, ValidationError) as err:
            _logger.error('button_get_login_token error occurred', exc_info=err)
            raise ValidationError(str(err)) from err

        return self.get_wizard_action()
