from . import (
    account_journal,
    account_move,
    account_move_line,
    account_tag,
    export_helper,
    ir_attachment,
    ir_report,
    jpk_account_tag,
    jpk_document_type,
    jpk_gtu,
    jpk_tax_office,
    product,
    res_company,
    res_partner,
)
