# Copyright 2009-2025 Noviat
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Spantech Accounting",
    "version": "16.0.1.1.0",
    "license": "AGPL-3",
    "author": "Noviat",
    "website": "https://www.noviat.com/",
    "category": "Spantech",
    "installable": True,
    "depends": [
        "spantech_base",
        "account",
        "account_banking_sepa_credit_transfer",
        "account_budget",
        "account_consolidation_mapping_base",
        "account_consolidation_mapping_encoding_aid",
        "account_followup",
        "account_financial_report",
        "account_invoice_margin_sale",
        "account_invoice_line_default",
        "account_payment_order",
        "account_move_tier_validation",
        "account_move_line_import",
        "account_move_line_report_xls",
        "account_move_line_search_extension",
        "account_move_line_product",
        "account_reports",
        "base_tier_validation_forward",
        "base_view_inheritance_extension",
        "sale_management",
        "spantech_partner",
        "trilab_invoice",
    ],
    "data": [
        "data/ir_sequence_data.xml",
        "data/product_data.xml",
        "data/mail_data.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/account_payment_mode_views.xml",
        "views/account_prepayment_views.xml",
        "views/account_tax_group_views.xml",
        "views/consolidation_period_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/report_external_layout_spantech.xml",
        "views/report_followup.xml",
        "views/report_invoice.xml",
        "wizards/account_payment_line_create_views.xml",
        "wizards/account_move_reversal_views.xml",
        "wizards/account_move_tree_reconciled_views.xml",
        "wizards/consolidation_period_copy_views.xml",
        "views/menu_views.xml",
        "security/prepayment_security.xml",
        "security/ir.model.access.csv",
    ],
}
