from . import account_move
from . import ir_attachment
from . import mail_thread
from . import product_template
from . import purchase_order
from . import res_company
from . import res_partner
from . import res_config_settings
from . import sale_order
from . import stock_picking
