# Do NOT update manually; changes here will be overwritten by Copier
_commit: v4.2
_src_path: git@github.com:Noviat-CI/addons-repo-template.git
ci_disable_autoinstall_modules: account_asset,l10n_be_coda
odoo_test_flavor: Enterprise
odoo_version: 16.0
org_slug: Noviat-Projects
rebel_module_groups: []
repo_name: Customer modules for Span-tech Project
repo_slug: span-tech_addons
repo_type: customer

