# Copyright 2009-2022 Noviat
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Spantech Install All",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "Noviat",
    "website": "https://www.noviat.com/",
    "category": "Spantech",
    "depends": [
        # noviat_addons
        "account_bank_transaction_numbering_scheme",
        "account_fiscal_position_constraints",
        "account_invoice_line_default",
        "account_journal_multi_company_mail_alias",
        "account_invoice_pay_filter",
        "account_journal_lock_date_nov",
        "account_move_line_import",
        "account_move_line_report_xls",
        "account_move_line_search_extension",
        "account_update_confirmed_invoice",
        "legacy_account_reporting_base",
        # "legacy_account_reporting_oe",
        # "legacy_account_reporting_oca",
        "account_partner_open_items_xlsx",
        "account_supplier_invoice_check_duplicates",
        "account_tax_constraints",
        "l10n_be_coa_multilang",
        "l10n_be_coda_advanced",
        "l10n_be_intrastat_product",
        "l10n_be_invoice_bba_customer",
        "l10n_be_partner_kbo_bce",
        "account_asset_management",
        "mail_alias_multi_company",
        # oca_addons
        "account_banking_sepa_credit_transfer",
        "account_financial_report",
        "auditlog",
        "partner_identification",
        "web_advanced_search",
        "web_dialog_size",
        "web_environment_ribbon",
        "web_m2x_options",
        "web_domain_field",
        "purchase_order_type",
        "res_company_code",
        "server_environment",
        "server_environment_ir_config_parameter",
        # span-tech_addons
        "spantech_account",
        "spantech_analytic",
        "spantech_anglo_saxon_conso_booking",
        "spantech_base",
        "spantech_helpdesk",
        "spantech_intercompany",
        "spantech_maintenance",
        "spantech_mrp",
        "spantech_partner",
        "spantech_poland",
        "spantech_product",
        "spantech_product_classification",
        "spantech_project",
        "spantech_purchase",
        "spantech_sale",
        "spantech_shipment_advice",
        "spantech_stock",
        "spantech_stock_valuation_report",
    ],
    "installable": True,
}
